

@startuml
left to right direction
skinparam packageStyle rectangle
skinparam backgroundColor #FDF6E3
skinparam usecaseBorderColor Black
skinparam usecaseBackgroundColor #FFF2CC
skinparam actorBorderColor Black
skinparam actorBackgroundColor #FDF6E3

actor Admin
actor Aslab

rectangle "Lab Management System" {
  usecase UC_Login as "Masuk"
  usecase UC_Register as "Daftar"
  usecase UC_Inventory as "Kelola Data\nAset & Bahan"
  usecase UC_Attendance as "Absensi\nAslab"
  usecase UC_Borrow as "Peminjaman\nAset & Bahan"
  usecase UC_Return as "Pengembalian\nAset & Bahan"
  usecase UC_Schedule as "Kelola\nJadwal"
  usecase UC_Report as "Laporan"
}

actor Mahasiswa
actor Dosen



Admin -right-> UC_Login
Admin -right-> UC_Inventory
Admin -right-> UC_Schedule
Admin -right-> UC_Return

Aslab -right-> UC_Login
Aslab -right-> UC_Attendance
Aslab -right-> UC_Borrow
Aslab -right-> UC_Return
Aslab -right-> UC_Register

Mahasiswa -left-> UC_Register
Mahasiswa -left-> UC_Login
Mahasiswa -left-> UC_Borrow

Dosen -left-> UC_Register
Dosen -left-> UC_Login
Dosen -left-> UC_Borrow


' Contoh include dan extend
UC_Borrow ..> UC_Return : <<include>>
UC_Inventory ..> UC_Report : <<extend>>

@enduml
