@startuml Automated Schedule Generation
!theme plain
skinparam maxMessageSize 120

title Sequence Diagram - Kelola Jadwal Piket Otomatis



actor "Admin" as Admin
boundary "Jadwal Piket Page" as Boundary
control "ScheduleController" as Control
entity "ScheduleEntity" as ScheduleEntity

Admin -> Boundary: Akses halaman jadwal piket
Boundary -> Control: Request jadwal piket
Control -> ScheduleEntity: Ambil jadwal piket
ScheduleEntity --> Control: Data jadwal
Control --> Boundary: Tampilkan jadwal piket

Admin -> Boundary: Klik generate jadwal
Boundary -> Control: Generate jadwal piket
Control -> ScheduleEntity: Generate & simpan jadwal random
alt Tidak ada aslab aktif
    Control --> Boundary: Tampilkan pesan "tidak ada aslab aktif"
else Ada aslab aktif
    ScheduleEntity --> Control: Success
    Control --> Boundary: Tampilkan jadwal baru
end

alt Edit manual
    Admin -> Boundary: Edit jadwal piket
    Boundary -> Control: Update jadwal piket
    Control -> ScheduleEntity: Simpan perubahan
    ScheduleEntity --> Control: Success
    Control --> Boundary: Tampilkan jadwal baru
end

@enduml
